### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by birchb** [nathanheffley/tailwindcss-card#1]
I'm attempting to use tailwindcss-card in a vue project. I followed the installations instructions but get this error on 'npm run dev':

`Module build failed: TypeError: addComponents is not a function
    at /Users/birchbrowning/Development/tailwindtest/node_modules/tailwindcss-card/index.js:18:5`

Here's my postcssrs.js:

`var tailwindcss = require("tailwindcss")

module.exports = {
  plugins: [
    // to edit target browsers: use "browserslist" field in package.json
    tailwindcss("tailwind.js"),
    require("tailwindcss-card")(),
    require("autoprefixer")
  ]
}`

I considered that the posscssrc.js file was not being imported correcly somewhere, but if I comment out the tailwindcss-card line, the app builds correctly, but the stacked card is not styled correctly, of course.

I'd love to make this work, as this seems like the right way to add components to tailwind. Any suggetions? Do you need any additional information? I used this template to start: [https://github.com/cesaramirez/popular-layouts](https://github.com/cesaramirez/popular-layouts).

**Comment by nathanheffley** [comment]
Hey @birchb, thanks for bringing this up! I'll try using that repo myself and see if I can reproduce the error. I'll let you know if I need any additional info

**Comment by birchb** [comment]
I did a little more investigation and see that Adam Wathan has changed the plugin API. See [https://github.com/tailwindcss/tailwindcss/pull/412](https://github.com/tailwindcss/tailwindcss/pull/412).

I'm not certain that I'm quite far enough along in my development to create a PR for you, but I'll take a look.

**Comment by nathanheffley** [comment]
I am still able to use this plugin with a fresh tailwind installation, and was not able to replicate your issue. If you're still experiencing it then please leave a comment here and I'll try it out again, or better yet submit a PR if you found a fix and I'll get it merged in.
